version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "dataverse-sdk/maintainers"
    assignees:
      - "dataverse-sdk/maintainers"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    
    # Group minor and patch updates
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    
    # Ignore specific packages if needed
    ignore:
      - dependency-name: "setuptools"
        versions: [">=60.0.0"]
    
    # Auto-merge configuration
    allow:
      - dependency-type: "direct:production"
        update-type: "version-update:semver-patch"
      - dependency-type: "direct:development"
        update-type: "version-update:semver-minor"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "dataverse-sdk/maintainers"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"

